name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run simulation headlessly and save plot
        run: |
          python CCR_Exposure_Simulation.py --no-show --save-fig exposure.png

      - name: Upload plot artifact
        uses: actions/upload-artifact@v4
        with:
          name: exposure-plot
          path: exposure.png
